# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

schedules:
- cron: "30 21 * * Mon-Fri"
  displayName: M-F 12:00 AM (UTC) daily build
  branches:
    include:
    - master
trigger:
      branches:
            include:
                   - '*'
   
pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'BDDLearningsProject/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install -DsuiteFile=$(suiteFile)'